Repository so2niko-students/js-22-1-vita, pull requests merged in 2023-09, with the labels that each got.

#2 #1create folder structure
  be/app.js
  be/index.js
  be/package.json
  be/routes/index.js
Labels: enhancement, good first issue

#4 BE: initialize express
  be/.gitignore
  be/app.js
  be/index.js
  be/package-lock.json
  be/package.json
Labels: enhancement, BE

#6 FE: check server status #5
  fe/src/App.js
Labels: enhancement, FE

#9 Write main docs 'How to start application' #8
  README.md
Labels: documentation

#10 BE--fix-CORS-policy-#7
  be/app.js
  be/package-lock.json
  be/package.json
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
Labels: BE

#12 Fix multiply call of server status #11
  fe/src/App.js
Labels: FE

#14 FE: Create component ServerStatus #13
  fe/src/App.js
  fe/src/RemoteIcon.js
  fe/src/ServerStatus.js
Labels: FE

#16 BE: server date and time routes #15
  be/app.js
  be/package-lock.json
  be/package.json
Labels: BE
